# Cert Manager for management of TLS certificates (only used if certbot.enabled and certbot.type == google)
cert-manager:
  enabled: false
  installCRDs: true
# Elastic file storage driver
aws-efs-csi-driver:
  enabled: false
  controller:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/workstation-eks-efs
  storageClasses:
  - name: efs-sc
    parameters:
      provisioningMode: efs-ap
      fileSystemId: fs-00000000000000000
      directoryPerms: "777"
# Nginx ingress system
ingress-nginx:
  controller:
    ingressClassResource:
      name: workstation-nginx
    # For the deployment
    labels:
      app: ingress-nginx
    # For the pods
    podLabels:
      app: ingress-nginx
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "1Gi"
        cpu: "500m"